//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlcantaraClient.Entities
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    
    public partial class Furniture
    {
        public int ID { get; set; }
        public int IdCategories { get; set; }
        public int IdFirms { get; set; }
        public string Name { get; set; }
        public decimal Cost { get; set; }
    
        public virtual CategoryReference CategoryReference { get; set; }
        public virtual Firm Firm { get; set; }

        public List<Review> Reviews
        {
            get
            {
                List<Review> reviews = CourseWorks_ThirdCourse_AlcantaraDbEntities.Instance.Reviews.ToList();
                reviews = reviews.Where(r => r.IdFurniture == ID).ToList();

                return reviews;
            }
        }

        public Double SummaryReviewsGrade
        {
            get
            {
                Double grade;

                try
                {
                    grade = Reviews.Sum(r => r.Grade) / Reviews.Count;
                }

                catch
                {
                    grade = 0;
                }

                return grade;
            }
        }

        public Furniture CreateCopy()
        {
            Furniture copy = new Furniture()
            {
                ID = ID,
                Name = Name,
                Firm = Firm,
                IdFirms = IdFirms,
                CategoryReference = CategoryReference,
                IdCategories = IdCategories,
                Cost = Cost
            };

            return copy;
        }

        public void MergeWithCopy(Furniture furniture)
        {
            ID = furniture.ID;
            Name = furniture.Name;
            Firm = furniture.Firm;
            IdFirms = furniture.IdFirms;
            CategoryReference = furniture.CategoryReference;
            IdCategories = furniture.IdCategories;
            Cost = furniture.Cost;
        }
    }
}
